[package]
name = "rust_socket_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }

[lib]
name = "ring"           # the library crate name users/tests will import
path = "src/lib.rs"

[[bin]]
name = "rust_socket_server"
path = "src/bin/main.rs"
